name: Unzip ZIP file

on:
  push:
    paths:
      - '**/*.zip'  # This will match ZIP files uploaded at any level in the repo

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Extract the ZIP file
      - name: Extract ZIP file
        run: |
          # Find all ZIP files
          for zip in $(find . -name '*.zip'); do
            echo "Unzipping $zip"
            unzip "$zip" -d "${zip%.zip}"
          done

      # Step 3: Commit and push extracted files
      - name: Commit and push extracted files
        run: |
          git config --global user.name "AKSHAY-PX-BYTES"
          git config --global user.email "apakshay582@gmail.com"
          git add .
          git commit -m "Extracted ZIP contents"
          git push
